import 'dart:typed_data';

import 'package:flutter/material.dart';
import 'package:provider/provider.dart';

import '../data/ronda_repository.dart';
import '../domain/ronda.dart';

class RondaDetailScreen extends StatelessWidget {
  const RondaDetailScreen({super.key, required this.ronda});

  final Ronda ronda;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text(ronda.templateName)),
      body: ListView(
        padding: const EdgeInsets.all(16),
        children: [
          Text(
            ronda.isCompleted ? 'Completed' : 'In progress',
            style: Theme.of(context).textTheme.labelLarge,
          ),
          const SizedBox(height: 4),
          Text(ronda.location.isEmpty ? 'No location' : ronda.location),
          if (ronda.completedAt != null) ...[
            const SizedBox(height: 4),
            Text('Finished ${ronda.completedAt!.toLocal()}'),
          ],
          const SizedBox(height: 16),
          if ((ronda.summary ?? '').isNotEmpty) ...[
            Text('LLM summary', style: Theme.of(context).textTheme.titleMedium),
            const SizedBox(height: 4),
            Text(
              ronda.summarySource == 'heuristic'
                  ? 'Generated without an API key (heuristic fallback)'
                  : 'Generated by LLM',
              style: Theme.of(context).textTheme.bodySmall,
            ),
            const SizedBox(height: 8),
            Card(
              child: Padding(
                padding: const EdgeInsets.all(16),
                child: Text(ronda.summary!),
              ),
            ),
            const SizedBox(height: 16),
          ],
          Text('Answers', style: Theme.of(context).textTheme.titleMedium),
          const SizedBox(height: 8),
          ...ronda.answers.map(
            (answer) => ListTile(
              contentPadding: EdgeInsets.zero,
              title: Text(answer.label),
              subtitle: Text(_answerText(answer)),
            ),
          ),
          const SizedBox(height: 8),
          Text(
            'Photos (${ronda.photos.length})',
            style: Theme.of(context).textTheme.titleMedium,
          ),
          const SizedBox(height: 8),
          Wrap(
            spacing: 8,
            runSpacing: 8,
            children: ronda.photos
                .map((photo) => _RemotePhoto(rondaId: ronda.id, photo: photo))
                .toList(),
          ),
        ],
      ),
    );
  }

  String _answerText(RondaAnswer answer) {
    if (answer.type == 'bool') {
      if (answer.boolValue == true) return 'Pass';
      if (answer.boolValue == false) return 'Fail';
      return 'Not answered';
    }
    if (answer.type == 'text') {
      return (answer.textValue ?? '').isEmpty ? 'No notes' : answer.textValue!;
    }
    return 'Photo item';
  }
}

class _RemotePhoto extends StatelessWidget {
  const _RemotePhoto({required this.rondaId, required this.photo});

  final String rondaId;
  final RondaPhoto photo;

  @override
  Widget build(BuildContext context) {
    final repo = context.read<RondaRepository>();
    return FutureBuilder<List<int>>(
      future: repo.photoBytes(rondaId, photo.id),
      builder: (context, snapshot) {
        if (!snapshot.hasData) {
          return Container(
            width: 96,
            height: 96,
            alignment: Alignment.center,
            color: Theme.of(context).colorScheme.surfaceContainerHighest,
            child: snapshot.hasError
                ? const Icon(Icons.broken_image_outlined)
                : const SizedBox(
                    width: 18,
                    height: 18,
                    child: CircularProgressIndicator(strokeWidth: 2),
                  ),
          );
        }
        return Image.memory(
          Uint8List.fromList(snapshot.data!),
          width: 96,
          height: 96,
          fit: BoxFit.cover,
        );
      },
    );
  }
}
